#!/usr/bin/env bash
# OS-aware dotfiles installer. Symlinks shared/ + the matching OS folder.
# Idempotent; backs up any existing real file to *.bak.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

case "$(uname -s)" in
  Darwin) OS=macos ;;
  Linux)  OS=linux ;;
  *) echo "Unsupported OS: $(uname -s)"; exit 1 ;;
esac
echo "Detected OS: $OS"

link() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [ -L "$dst" ]; then rm "$dst"
  elif [ -e "$dst" ]; then echo "  backup: $dst -> $dst.bak"; mv "$dst" "$dst.bak"; fi
  ln -s "$src" "$dst"
  echo "  link:   $dst"
}

# 1) home-level dotfiles from shared/ and $OS/ (top-level dotfiles only)
link_home_dir() {
  local base="$1"
  [ -d "$base" ] || return 0
  for f in "$base"/.*; do
    local n; n="$(basename "$f")"
    { [ "$n" = "." ] || [ "$n" = ".." ] || [ "$n" = ".vim" ]; } && continue
    [ -f "$f" ] || continue
    case "$n" in *.template) continue;; esac
    link "$f" "$HOME/$n"
  done
}
echo "Linking home dotfiles..."
link_home_dir "$DIR/shared"
link_home_dir "$DIR/$OS"

# .vim dir (shared)
[ -d "$DIR/shared/.vim" ] && link "$DIR/shared/.vim" "$HOME/.vim"

# 2) ~/.config trees (shared + OS), skipping .template files
echo "Linking ~/.config..."
for base in "$DIR/shared/config" "$DIR/$OS/config"; do
  [ -d "$base" ] || continue
  while IFS= read -r -d '' f; do
    # zed settings.json is generated by merge below, not symlinked
    case "$f" in *.template|*/zed/settings.json) continue;; esac
    link "$f" "$HOME/.config/${f#"$base"/}"
  done < <(find "$base" -type f -print0)
done

# 2b) Zed settings: merge public base + local MCP snippet into one real file
ZED_BASE="$DIR/shared/config/zed/settings.json"
ZED_MCP="$DIR/local/zed-context-servers.json"
ZED_OUT="$HOME/.config/zed/settings.json"
if [ -f "$ZED_BASE" ]; then
  mkdir -p "$(dirname "$ZED_OUT")"
  if [ -f "$ZED_MCP" ]; then
    [ -L "$ZED_OUT" ] && rm "$ZED_OUT"
    [ -e "$ZED_OUT" ] && mv "$ZED_OUT" "$ZED_OUT.bak"
    python3 "$DIR/scripts/merge-zed.py" "$ZED_BASE" "$ZED_MCP" "$ZED_OUT"
    echo "  merged Zed settings (base + local MCP) -> $ZED_OUT"
  else
    link "$ZED_BASE" "$ZED_OUT"   # no local MCP: use public base directly
  fi
fi

# 3) VSCodium settings/keybindings (OS-specific user dir)
if [ -d "$DIR/vscodium" ]; then
  echo "Linking VSCodium config..."
  case "$OS" in
    macos) VU="$HOME/Library/Application Support/VSCodium/User" ;;
    linux) VU="$HOME/.config/VSCodium/User" ;;
  esac
  for f in settings.json keybindings.json; do
    [ -f "$DIR/vscodium/$f" ] && link "$DIR/vscodium/$f" "$VU/$f"
  done
  [ -f "$DIR/vscodium/argv.json" ] && link "$DIR/vscodium/argv.json" "$HOME/.vscode-oss/argv.json"
fi

# 4) local/ private files (secrets, corp, identity) — from your private repo
if [ -d "$DIR/local" ]; then
  echo "Linking local/ private files..."
  [ -f "$DIR/local/secrets" ]             && link "$DIR/local/secrets"             "$HOME/.secrets"
  [ -f "$DIR/local/localrc" ]             && link "$DIR/local/localrc"             "$HOME/.localrc"
  [ -f "$DIR/local/gitconfig.local" ]     && link "$DIR/local/gitconfig.local"     "$HOME/.gitconfig.local"
  [ -f "$DIR/local/ssh-config" ]          && link "$DIR/local/ssh-config"          "$HOME/.ssh/config"
  [ -d "$DIR/local/npmrcs" ]              && link "$DIR/local/npmrcs"              "$HOME/.npmrcs"
  [ -f "$DIR/local/claude-settings.json" ] && link "$DIR/local/claude-settings.json" "$HOME/.claude/settings.json"
else
  echo "No local/ dir — clone your private repo into $DIR/local for secrets/corp config."
fi

# 5) git-leaks pre-commit hook
if [ -f "$DIR/hooks/pre-commit" ]; then
  cp "$DIR/hooks/pre-commit" "$DIR/.git/hooks/pre-commit"
  chmod +x "$DIR/.git/hooks/pre-commit"
  echo "Installed gitleaks pre-commit hook."
fi

cat <<EOF

Done.
Next steps:
  1) Secrets/corp config: clone your private repo into $DIR/local (or build it
     from local/*.template), then re-run ./install.sh to symlink it.
  2) Install VSCodium extensions:
     cat vscodium/extensions.txt | xargs -L1 codium --install-extension
EOF
